/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/caicloud/temp-model-registry/pkg/apis/modeljob/v1alpha1"
	scheme "github.com/caicloud/temp-model-registry/pkg/clientset/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ModelJobsGetter has a method to return a ModelJobInterface.
// A group's client should implement this interface.
type ModelJobsGetter interface {
	ModelJobs(namespace string) ModelJobInterface
}

// ModelJobInterface has methods to work with ModelJob resources.
type ModelJobInterface interface {
	Create(ctx context.Context, modelJob *v1alpha1.ModelJob, opts v1.CreateOptions) (*v1alpha1.ModelJob, error)
	Update(ctx context.Context, modelJob *v1alpha1.ModelJob, opts v1.UpdateOptions) (*v1alpha1.ModelJob, error)
	UpdateStatus(ctx context.Context, modelJob *v1alpha1.ModelJob, opts v1.UpdateOptions) (*v1alpha1.ModelJob, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ModelJob, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ModelJobList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ModelJob, err error)
	ModelJobExpansion
}

// modelJobs implements ModelJobInterface
type modelJobs struct {
	client rest.Interface
	ns     string
}

// newModelJobs returns a ModelJobs
func newModelJobs(c *ModeljobsV1alpha1Client, namespace string) *modelJobs {
	return &modelJobs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the modelJob, and returns the corresponding modelJob object, and an error if there is any.
func (c *modelJobs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ModelJob, err error) {
	result = &v1alpha1.ModelJob{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("modeljobs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ModelJobs that match those selectors.
func (c *modelJobs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ModelJobList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ModelJobList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("modeljobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested modelJobs.
func (c *modelJobs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("modeljobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a modelJob and creates it.  Returns the server's representation of the modelJob, and an error, if there is any.
func (c *modelJobs) Create(ctx context.Context, modelJob *v1alpha1.ModelJob, opts v1.CreateOptions) (result *v1alpha1.ModelJob, err error) {
	result = &v1alpha1.ModelJob{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("modeljobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(modelJob).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a modelJob and updates it. Returns the server's representation of the modelJob, and an error, if there is any.
func (c *modelJobs) Update(ctx context.Context, modelJob *v1alpha1.ModelJob, opts v1.UpdateOptions) (result *v1alpha1.ModelJob, err error) {
	result = &v1alpha1.ModelJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("modeljobs").
		Name(modelJob.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(modelJob).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *modelJobs) UpdateStatus(ctx context.Context, modelJob *v1alpha1.ModelJob, opts v1.UpdateOptions) (result *v1alpha1.ModelJob, err error) {
	result = &v1alpha1.ModelJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("modeljobs").
		Name(modelJob.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(modelJob).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the modelJob and deletes it. Returns an error if one occurs.
func (c *modelJobs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("modeljobs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *modelJobs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("modeljobs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched modelJob.
func (c *modelJobs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ModelJob, err error) {
	result = &v1alpha1.ModelJob{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("modeljobs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
