/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kleveross/klever-model-registry/pkg/apis/modeljob/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeModelJobs implements ModelJobInterface
type FakeModelJobs struct {
	Fake *FakeKleverossV1alpha1
	ns   string
}

var modeljobsResource = schema.GroupVersionResource{Group: "kleveross.io", Version: "v1alpha1", Resource: "modeljobs"}

var modeljobsKind = schema.GroupVersionKind{Group: "kleveross.io", Version: "v1alpha1", Kind: "ModelJob"}

// Get takes name of the modelJob, and returns the corresponding modelJob object, and an error if there is any.
func (c *FakeModelJobs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ModelJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(modeljobsResource, c.ns, name), &v1alpha1.ModelJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ModelJob), err
}

// List takes label and field selectors, and returns the list of ModelJobs that match those selectors.
func (c *FakeModelJobs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ModelJobList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(modeljobsResource, modeljobsKind, c.ns, opts), &v1alpha1.ModelJobList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ModelJobList{ListMeta: obj.(*v1alpha1.ModelJobList).ListMeta}
	for _, item := range obj.(*v1alpha1.ModelJobList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested modelJobs.
func (c *FakeModelJobs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(modeljobsResource, c.ns, opts))

}

// Create takes the representation of a modelJob and creates it.  Returns the server's representation of the modelJob, and an error, if there is any.
func (c *FakeModelJobs) Create(ctx context.Context, modelJob *v1alpha1.ModelJob, opts v1.CreateOptions) (result *v1alpha1.ModelJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(modeljobsResource, c.ns, modelJob), &v1alpha1.ModelJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ModelJob), err
}

// Update takes the representation of a modelJob and updates it. Returns the server's representation of the modelJob, and an error, if there is any.
func (c *FakeModelJobs) Update(ctx context.Context, modelJob *v1alpha1.ModelJob, opts v1.UpdateOptions) (result *v1alpha1.ModelJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(modeljobsResource, c.ns, modelJob), &v1alpha1.ModelJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ModelJob), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeModelJobs) UpdateStatus(ctx context.Context, modelJob *v1alpha1.ModelJob, opts v1.UpdateOptions) (*v1alpha1.ModelJob, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(modeljobsResource, "status", c.ns, modelJob), &v1alpha1.ModelJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ModelJob), err
}

// Delete takes name of the modelJob and deletes it. Returns an error if one occurs.
func (c *FakeModelJobs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(modeljobsResource, c.ns, name), &v1alpha1.ModelJob{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeModelJobs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(modeljobsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ModelJobList{})
	return err
}

// Patch applies the patch and returns the patched modelJob.
func (c *FakeModelJobs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ModelJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(modeljobsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ModelJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ModelJob), err
}
