// +build !ignore_autogenerated

/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversionBaseSpec) DeepCopyInto(out *ConversionBaseSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversionBaseSpec.
func (in *ConversionBaseSpec) DeepCopy() *ConversionBaseSpec {
	if in == nil {
		return nil
	}
	out := new(ConversionBaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversionSource) DeepCopyInto(out *ConversionSource) {
	*out = *in
	if in.MMdnn != nil {
		in, out := &in.MMdnn, &out.MMdnn
		*out = new(MMdnnSpec)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversionSource.
func (in *ConversionSource) DeepCopy() *ConversionSource {
	if in == nil {
		return nil
	}
	out := new(ConversionSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtractionSource) DeepCopyInto(out *ExtractionSource) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtractionSource.
func (in *ExtractionSource) DeepCopy() *ExtractionSource {
	if in == nil {
		return nil
	}
	out := new(ExtractionSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MMdnnSpec) DeepCopyInto(out *MMdnnSpec) {
	*out = *in
	out.ConversionBaseSpec = in.ConversionBaseSpec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MMdnnSpec.
func (in *MMdnnSpec) DeepCopy() *MMdnnSpec {
	if in == nil {
		return nil
	}
	out := new(MMdnnSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelJob) DeepCopyInto(out *ModelJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelJob.
func (in *ModelJob) DeepCopy() *ModelJob {
	if in == nil {
		return nil
	}
	out := new(ModelJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelJobList) DeepCopyInto(out *ModelJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelJobList.
func (in *ModelJobList) DeepCopy() *ModelJobList {
	if in == nil {
		return nil
	}
	out := new(ModelJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelJobSource) DeepCopyInto(out *ModelJobSource) {
	*out = *in
	if in.Extraction != nil {
		in, out := &in.Extraction, &out.Extraction
		*out = new(ExtractionSource)
		**out = **in
	}
	if in.Conversion != nil {
		in, out := &in.Conversion, &out.Conversion
		*out = new(ConversionSource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelJobSource.
func (in *ModelJobSource) DeepCopy() *ModelJobSource {
	if in == nil {
		return nil
	}
	out := new(ModelJobSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelJobSpec) DeepCopyInto(out *ModelJobSpec) {
	*out = *in
	if in.DesiredTag != nil {
		in, out := &in.DesiredTag, &out.DesiredTag
		*out = new(string)
		**out = **in
	}
	in.ModelJobSource.DeepCopyInto(&out.ModelJobSource)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelJobSpec.
func (in *ModelJobSpec) DeepCopy() *ModelJobSpec {
	if in == nil {
		return nil
	}
	out := new(ModelJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelJobStatus) DeepCopyInto(out *ModelJobStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelJobStatus.
func (in *ModelJobStatus) DeepCopy() *ModelJobStatus {
	if in == nil {
		return nil
	}
	out := new(ModelJobStatus)
	in.DeepCopyInto(out)
	return out
}
