/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	modeljobv1alpha1 "github.com/caicloud/temp-model-registry/pkg/apis/modeljob/v1alpha1"
	versioned "github.com/caicloud/temp-model-registry/pkg/clientset/clientset/versioned"
	internalinterfaces "github.com/caicloud/temp-model-registry/pkg/clientset/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/caicloud/temp-model-registry/pkg/clientset/listers/modeljob/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ModelJobInformer provides access to a shared informer and lister for
// ModelJobs.
type ModelJobInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ModelJobLister
}

type modelJobInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewModelJobInformer constructs a new informer for ModelJob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewModelJobInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredModelJobInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredModelJobInformer constructs a new informer for ModelJob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredModelJobInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ModeljobsV1alpha1().ModelJobs(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ModeljobsV1alpha1().ModelJobs(namespace).Watch(options)
			},
		},
		&modeljobv1alpha1.ModelJob{},
		resyncPeriod,
		indexers,
	)
}

func (f *modelJobInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredModelJobInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *modelJobInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&modeljobv1alpha1.ModelJob{}, f.defaultInformer)
}

func (f *modelJobInformer) Lister() v1alpha1.ModelJobLister {
	return v1alpha1.NewModelJobLister(f.Informer().GetIndexer())
}
